export const WORKFLOW_SYSTEM = {
	DISCORD_MESSAGE_LIMIT: 4096,
	DISCORD_READ_LIMIT: 50,
	SLACK_MESSAGE_LIMIT: 4096,
	SLACK_READ_LIMIT: 50,
	TELEGRAM_MESSAGE_LIMIT: 4096,
	YOUTUBE_TRANSCRIBE_LIMIT: 3600, // 1 hour in seconds
	WORKFLOW_EXECUTION_COST: 0.5, // Cost in wallet for each workflow execution in INR
};
