export const agents = [
	{
		id: 'c',
		name: 'Customer Support Bot',
		icon: 'C',
		color: 'bg-gradient-to-r from-blue-500 to-purple-600',
		specialization: 'customer support',
	},
	{
		id: 'd',
		name: 'Data Analytics Agent',
		icon: 'D',
		color: 'bg-gradient-to-r from-blue-500 to-purple-600',
		specialization: 'data analysis',
	},
	{
		id: 'm',
		name: 'Marketing Automator',
		icon: 'M',
		color: 'bg-gradient-to-r from-blue-500 to-purple-600',
		specialization: 'marketing',
	},
	{
		id: 'i',
		name: 'Invoice Processor',
		icon: 'I',
		color: 'bg-gradient-to-r from-blue-500 to-purple-600',
		specialization: 'invoice processing',
	},
	{
		id: 'h',
		name: 'HR Assistant',
		icon: 'H',
		color: 'bg-gradient-to-r from-blue-500 to-purple-600',
		specialization: 'hr assistance',
	},
	{
		id: 'it',
		name: 'IT Helpdesk',
		icon: 'I',
		color: 'bg-gradient-to-r from-blue-500 to-purple-600',
		specialization: 'it helpdesk',
	},
	{
		id: 's',
		name: 'Social Media Manager',
		icon: 'S',
		color: 'bg-gradient-to-r from-blue-500 to-purple-600',
		specialization: 'social media',
	},
	{
		id: 'seo',
		name: 'SEO Optimizer',
		icon: 'S',
		color: 'bg-gradient-to-r from-blue-500 to-purple-600',
		specialization: 'seo optimization',
	},
	{
		id: 'crm',
		name: 'CRM Sync Agent',
		icon: 'C',
		color: 'bg-gradient-to-r from-blue-500 to-purple-600',
		specialization: 'crm synchronization',
	},
	{
		id: 'e',
		name: 'E-commerce Assistant',
		icon: 'E',
		color: 'bg-gradient-to-r from-blue-500 to-purple-600',
		specialization: 'e-commerce',
	},
];
